apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-1
  name: api-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-1
  template:
    metadata:
      labels:
        app: api-1
    spec:
      containers:
      - name: api-1-containter
        image: tutum/hello-world
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: config-map-api-1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-1
  name: api-1-service
spec:
  type: NodePort
  ports:
  - name: webport
    port: 80
    targetPort: 80
  selector:
    app: api-1    
