apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  labels:
    kcert.dev/ingress: "managed"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/from-to-www-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = '' ) {
        rewrite ^ https://www.$request_uri permanent;
      }
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - invalid.agileguru.org
    secretName: ingress-host-secret
  rules:
  - host: invalid.agileguru.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: api-1-service
            port: 
                number: 80       
      - path: /app
        pathType: Prefix
        backend:
          service: 
            name: api-1-service
            port: 
                number: 80                           